[build]
  command = "sh ./build.sh"
  functions = "functions"

[build.environment]
  GO_IMPORT_PATH = "github.com/cassis163/personal-site"
  GO111MODULE = "on"
  GO_VERSION = "1.21.2"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200
