[build]
  command = "go install github.com/a-h/templ/cmd/templ@latest && templ generate ./src && sh ./build.sh"
  functions = "functions"
  publish = "public"

[build.environment]
  GO_IMPORT_PATH = "github.com/cassis163/personal-site"
  GO111MODULE = "on"
  GO_VERSION = "1.21.2"
